import argparse
import sys
from pathlib import Path

import pandas as pd

CURRENT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = CURRENT_DIR.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.load_data import DataStore


def parse_args():
    parser = argparse.ArgumentParser(
        description="Validate ASM accuracy snapshots and emit alerts suitable for CI."
    )
    parser.add_argument(
        "--input",
        type=Path,
        default=Path("reports/asm_summary_history.csv"),
        help="CSV file generated by scripts/report.py or scripts/showcase.py.",
    )
    parser.add_argument(
        "--airline",
        action="append",
        help="Limit checks to these airlines (defaults to all airlines in the log).",
    )
    parser.add_argument(
        "--estimate-threshold",
        type=float,
        default=0.5,
        help="Fail when >= this share of ASM relies on equipment estimates.",
    )
    parser.add_argument(
        "--unknown-threshold",
        type=float,
        default=0.2,
        help="Fail when >= this share of ASM is from unknown seat sources.",
    )
    parser.add_argument(
        "--fail-on-alert",
        action="store_true",
        help="Exit with status 1 when alerts are present (default: warn only).",
    )
    parser.add_argument(
        "--require-data",
        action="store_true",
        help="Exit with status 1 if the input file is missing or empty.",
    )
    return parser.parse_args()


def load_history(path: Path) -> pd.DataFrame:
    if not path.exists():
        return pd.DataFrame()
    df = pd.read_csv(path)
    if df.empty:
        return df
    required = {
        "Airline",
        "Seat Source",
        "ASM Share Value",
        "ASM Share",
        "Total Seats",
        "Total ASM",
        "Generated At",
    }
    missing = required.difference(df.columns)
    if missing:
        raise ValueError(f"History file is missing required columns: {', '.join(sorted(missing))}")
    df["Generated At"] = pd.to_datetime(df["Generated At"], utc=True, errors="coerce")
    df["ASM Share Value"] = pd.to_numeric(df["ASM Share Value"], errors="coerce").fillna(0.0)
    df["Total ASM"] = pd.to_numeric(df["Total ASM"], errors="coerce").fillna(0.0)
    df["Total Seats"] = pd.to_numeric(df["Total Seats"], errors="coerce").fillna(0.0)
    return df


def latest_snapshot(history: pd.DataFrame, airline: str) -> pd.DataFrame:
    subset = history[history["Airline"] == airline]
    if subset.empty:
        return pd.DataFrame()
    latest_ts = subset["Generated At"].max()
    latest = subset[subset["Generated At"] == latest_ts].copy()
    return latest


def main():
    args = parse_args()
    history = load_history(args.input)

    if history.empty:
        message = f"No ASM summaries found at {args.input}."
        if args.require_data:
            print(message, file=sys.stderr)
            sys.exit(1)
        print(f"{message} Skipping check.")
        sys.exit(0)

    airlines = args.airline or sorted(history["Airline"].unique())
    datastore = DataStore()

    alerts_triggered = {}
    missing = []

    for airline in airlines:
        snapshot = latest_snapshot(history, airline)
        if snapshot.empty:
            missing.append(airline)
            continue
        alerts = datastore.detect_asm_alerts(
            snapshot,
            estimate_threshold=args.estimate_threshold,
            unknown_threshold=args.unknown_threshold,
        )
        if alerts:
            alerts_triggered[airline] = alerts

    if missing:
        print("No snapshot data for:", ", ".join(missing))

    if not alerts_triggered:
        print("ASM quality check passed – no alerts triggered.")
        sys.exit(0)

    print("ASM quality alerts detected:")
    for airline, alerts in alerts_triggered.items():
        print(f"- {airline}:")
        for alert in alerts:
            print(f"    • {alert}")

    if args.fail_on_alert:
        sys.exit(1)


if __name__ == "__main__":
    main()
